# Cleaning Ecuador's Dataset

## Import Packages

Style Notes:
*   Always import your libraries and packages at the top of your code to avoid name clashes, undefined behavior, and to let everyone know what they need to install to run the whole script.
*   Constant's names are usually written in "all caps" to signal other programmers (and oneself) that their values should not be changed throughout the code (under normal circumstances, at least). In other languages there are ways to yield errors if attempts to modify them occur (making them true constants).
*   Constants should also be defined at the top of your code, so that they are clearly visible to collaborators, and defined throughout the whole codeset.

In [9]:
###############################################################################
# Make sure to change username for the correct path to be setup.
#   TH: Thien-An Ha
#   HS: Héctor M. Sánchez C.
#   TL: Tomás León
###############################################################################
USER = 'TH'
###############################################################################
import pandas as pd

## Setup Paths

Style Notes: 
*   Setting up the path separate from the filename will help when we want to export the results of the cleaning.

In [2]:
###############################################################################
# Add user ID's if more people are gonna work on the dataset. Make sure to
#   change the USER constant (first line of the notebook) so that the path 
#   is set correctly.
###############################################################################
if USER == 'TH':
    FILE = 'BAS_20190611_Reporte_colectas_insectario_ADB_V03.xlsx'
    PATH = r'C:\Users\Daoanh\Documents\Berkeley\Summer 2019\INSPI'
    FILEPATH = PATH + '\\' + FILE
    print(FILEPATH)
elif USER == 'HS':
    FILE = 'BAS_20190611_Reporte_colectas_insectario_ADB_V02.xlsx'
    PATH = '/Volumes/marshallShare/Ecuador/'
    FILEPATH = PATH + FILE
    print(FILEPATH)
elif USER == 'TL':
    (FILE, PATH, FILEPATH) = [None for i in range(3)]
    print('Paths for comrade Tomas have not been setup yet.')
else:
    (FILE, PATH, FILEPATH) = [None for i in range(3)]
    print('Invalid username. Paths are set to "None".')

C:\Users\Daoanh\Documents\Berkeley\Summer 2019\INSPI\BAS_20190611_Reporte_colectas_insectario_ADB_V03.xlsx

## Start working on the dataset

General Notes:
*   This line takes some time because the dataset is large. Wait until the evaluation is over!

In [5]:
###############################################################################
# Load the dataset with the date columns being parsed as dateobjects.
###############################################################################

data_se = pd.read_excel(
    FILEPATH, 
    sheet_name='1.socio_económico_SATVEC',
    parse_dates=[0, 6, 33]
)

Coding Notes:
*   The `'.'` in most programming languages is used to denote that you're calling the method of an instance of an object (I'll explain this a bit better once we're back). In general terms it can be read as `object.method()`, where we're asking the `object` to perform the `method` action. For example: `dataImmTAO.head()` tells the dataframe object `dataImmTAO` that it should perform the `head()` action, which is coded in its class' definition (this also needs some 'in-person' explaining, but it's not difficult).

In [7]:
data_se.head()
data_se.tail()

,Año,Parroquia,Provincia,Distrito,Circuito,Subcircuito,Fecha de colecta,Código provincia,Código distrito,Código circuito,...,malla protectora,sitios de reproducción,codigo muestreo anterior,fecha digitación,digitador,iep1_id,idp1_id,nombre proyecto,observación encabezado,observaciones
46560,2017,Guayaquil,Guayas,Nueva Prosperina,Paraíso De La Flor,Paraíso De La Flor 1,2017-08-10 00:00:00,9,8,3,...,No,No,NaN,2017-11-10,Guillermo André Jaramillo Nogales,1923,48025,Cirev,NaN,NaN
46561,2017,Guayaquil,Guayas,Nueva Prosperina,Paraíso De La Flor,Paraíso De La Flor 1,2017-08-10 00:00:00,9,8,3,...,Si,No,NaN,2017-11-10,Guillermo André Jaramillo Nogales,1923,48026,Cirev,NaN,NaN
46562,2017,Guayaquil,Guayas,Nueva Prosperina,Paraíso De La Flor,Paraíso De La Flor 1,2017-08-10 00:00:00,9,8,3,...,No,No,NaN,2017-11-10,Guillermo André Jaramillo Nogales,1923,48027,Cirev,NaN,NaN
46563,2017,Guayaquil,Guayas,Nueva Prosperina,Paraíso De La Flor,Paraíso De La Flor 1,2017-08-10 00:00:00,9,8,3,...,No,No,NaN,2017-11-10,Guillermo André Jaramillo Nogales,1923,48021,Cirev,NaN,NaN
46564,2017,Guayaquil,Guayas,Nueva Prosperina,Paraíso De La Flor,Paraíso De La Flor 1,2017-08-10 00:00:00,9,8,3,...,No,No,NaN,2017-11-10,Guillermo André Jaramillo Nogales,1923,48005,Cirev,NaN,NaN

In [10]:
data_supply = pd.read_excel(
    FILEPATH, 
    sheet_name='1.tipo_suministro',
    parse_dates=[0, 6]
)

In [11]:
data_supply.head()

,Año,Parroquia,Provincia,Distrito,Circuito,Subcircuito,Fecha de colecta,Código provincia,Código distrito,Código circuito,Código subcircuito,Código casa,Tipo de suministro,iep1_id,idp1_id
0,196,Huaquillas,El Oro,Huaquillas,Hualtaco,No identificado,28/03/196,7,5,6,0,1,Agua Potable,1906,47686
1,2013,Guayaquil,Guayas,Nueva Prosperina,Nueva Prosperina,Nueva Prosperina 1,2013-01-14 00:00:00,9,8,1,1,1,Agua Potable,783,30906
2,2013,Guayaquil,Guayas,Nueva Prosperina,Nueva Prosperina,Nueva Prosperina 1,2013-01-14 00:00:00,9,8,1,1,3,Agua Potable,783,30919
3,2013,Guayaquil,Guayas,Nueva Prosperina,Nueva Prosperina,Nueva Prosperina 1,2013-01-14 00:00:00,9,8,1,1,4,Agua Potable,783,30923
4,2013,Guayaquil,Guayas,Nueva Prosperina,Nueva Prosperina,Nueva Prosperina 1,2013-01-14 00:00:00,9,8,1,1,5,Agua Potable,783,30931

In [13]:
data_wc = pd.read_excel(
    FILEPATH, 
    sheet_name='1.recipientes_agua',
    parse_dates=[0, 4]
)

In [14]:
data_wc.head()

,Año,Cantón,Parroquia,Provincia,Distrito,Circuito,Subcircuito,Fecha de colecta,Código provincia,Código distrito,Código circuito,Código subcircuito,Código casa,Material de recipiente,No. de recipientes,idp1_id,iep1_id
0,196,Huaquillas,Huaquillas,El Oro,Huaquillas,Hualtaco,No identificado,28/03/196,7,5,6,0,1,Plástico,2,47686,1906
1,2013,Manta,Manta,Manabí,Manta,Centro,Centro 1,2013-01-14 00:00:00,13,2,7,1,18,Otro,7,21943,534
2,2013,Manta,Manta,Manabí,Manta,Centro,Centro 1,2013-01-14 00:00:00,13,2,7,1,28,Otro,1,21969,534
3,2013,Manta,Manta,Manabí,Manta,Centro,Centro 1,2013-01-14 00:00:00,13,2,7,1,24,Plástico,4,21963,534
4,2013,Manta,Manta,Manabí,Manta,Centro,Centro 1,2013-01-14 00:00:00,13,2,7,1,29,Otro,1,21970,534

In [15]:
df = [data_se, data_supply, data_wc]